services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app         # Le Bind Mount : lie ton code local au conteneur 
      - /app/node_modules       # Empêche Docker d'écraser tes modules installés
    ports:
      - "5173:5173"             # Port par défaut de Vite
    networks:
      - frontend-net
    command: sh -c "npm install && npm run dev -- --host"

  api1:
    build: ./api1
    networks:
      - frontend-net
      - backend1-net
    depends_on:
      - db1

  db1:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - api1-db-data:/data/db # Persistance des données [cite: 54]
    networks:
      - backend1-net

  api2:
    build: ./api2
    networks:
      - frontend-net
      - backend2-net
    depends_on:
      - db2

  db2:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - api2-db-data:/data/db
    networks:
      - backend2-net

networks:
  frontend-net:
  backend1-net:
  backend2-net:

volumes:
  api1-db-data:
  api2-db-data: